apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: front-end
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.2.22
    chart: grafana
    helm:
      parameters:
        - name: 'admin.password'
          value: admin
        - name: 'ingress.enabled'
          value: 'true'
        - name: 'ingress.hostname'
          value: $ARGOCD_APP_NAME-demo.difinative.com
