apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: front-end
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.2.22
    chart: grafana
    helm:
      parameters:
        - name: 'ingress.hostname'
          value: $ARGOCD_APP_NAME.difinative.com